# Generated by Django 6.0.6 on 2026-06-20 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actors/')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='director/')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('duration', models.IntegerField(help_text='minutes')),
                ('rating', models.FloatField(default=0.0)),
                ('banner', models.ImageField(null=True, upload_to='movies/banners')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movies/thumbnail')),
                ('language', models.CharField(choices=[('farsi', 'فارسی (دوبله)'), ('subtitle', 'زیرنویس فارسی'), ('english', 'زیرنویس انگلیسی'), ('original', 'زبان اصلی'), ('multi', 'چند زبانه')], default='english', max_length=20)),
                ('age_rate', models.CharField(choices=[('all', 'همه سنین'), ('12+', '۱۲+'), ('13+', '۱۳+'), ('15+', '۱۵+'), ('18+', '۱۸+')], default='all', max_length=5)),
                ('video', models.URLField(blank=True, null=True)),
                ('is_trending', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('actors', models.ManyToManyField(related_name='movies', to='catalog.actor')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country')),
                ('directors', models.ManyToManyField(related_name='movies', to='catalog.director')),
                ('genres', models.ManyToManyField(related_name='movies', to='catalog.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Series/')),
                ('banner', models.ImageField(null=True, upload_to='Series/banners')),
                ('language', models.CharField(choices=[('farsi', 'فارسی (دوبله)'), ('subtitle', 'زیرنویس فارسی'), ('english', 'زیرنویس انگلیسی'), ('original', 'زبان اصلی'), ('multi', 'چند زبانه')], default='english', max_length=20)),
                ('year', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('age_rate', models.CharField(choices=[('all', 'همه سنین'), ('12+', '۱۲+'), ('13+', '۱۳+'), ('15+', '۱۵+'), ('18+', '۱۸+')], default='all', max_length=5)),
                ('is_trending', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('actors', models.ManyToManyField(related_name='series', to='catalog.actor')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.country')),
                ('directors', models.ManyToManyField(related_name='series', to='catalog.director')),
                ('genres', models.ManyToManyField(related_name='series', to='catalog.genre')),
            ],
            options={
                'verbose_name': 'Series',
                'verbose_name_plural': 'Series',
                'ordering': ['-year', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('number', models.IntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='catalog.series')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['number'],
                'unique_together': {('series', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('update_at', models.DateField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('duration', models.IntegerField()),
                ('number', models.IntegerField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.season')),
            ],
            options={
                'verbose_name': 'episode',
                'verbose_name_plural': 'episodes',
                'ordering': ['number'],
                'unique_together': {('season', 'number')},
            },
        ),
    ]
