# Generated by Django 6.0.6 on 2026-06-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
