# Generated by Django 6.0.6 on 2026-07-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_series_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_rate',
            field=models.CharField(choices=[('all', 'همه سنین'), ('12+', '۱۲+'), ('13+', '۱۳+'), ('15+', '۱۵+'), ('18+', '۱۸+')], db_column='age_rate', default='all', max_length=5),
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='age_rate',
            new_name='age_rating',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='age_rate',
            new_name='age_rating',
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='directors/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='series',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
